FROM newrelic/network-agent:latest

USER root
RUN setcap -r /usr/local/bin/newrelic-network-agent

EXPOSE 8082

USER newrelic-network-agent
ENTRYPOINT ["newrelic-network-agent", "-listen", "off", "-mapping", "/etc/newrelic-network-agent/config.json", "-geo", "/etc/newrelic-network-agent/GeoLite2-Country.mmdb", "-udrs", "/etc/newrelic-network-agent/udr.csv", "-api_devices", "/etc/newrelic-network-agent/devices.json", "-asn", "/etc/newrelic-network-agent/GeoLite2-ASN.mmdb", "-log_level", "info", "-geo_region_map", "/etc/newrelic-network-agent/ch_region_mapping.csv.gz", "-geo_city_map", "/etc/newrelic-network-agent/ch_city_mapping.csv.gz"]