version: "3.9"
services:
  newrelic-network-agent:
    image: newrelic/network-agent:latest
    container_name: newrelic-network-agent
    restart: unless-stopped
    volumes:
      - ${SNMP_PATH}:/snmp.yaml ## Make SNMP_PATH a path to your local snmp.yaml config.
    environment: ## Set these env vars
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
      - NR_ACCOUNT_ID=${NR_ACCOUNT_ID}
      - NR_REGION=${NR_REGION}
    command:
      - -snmp=/snmp.yaml
      - -metrics=jchf
      - -tee_logs=true
      - nr1.snmp
    network_mode: host
